env:
  TERM: xterm-256color

dimensions:
  columns: 200
  lines: 60

padding:
  x: 2
  y: 2

tabspaces: 8

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: Source Code Pro for Powerline
    style: Medium

  bold:
    family: Source Code Pro for Powerline

  italic:
    family: Source Code Pro for Powerline

  size: 14.0

  offset:
    x: 0.0
    y: 0.0

  glyph_offset:
    x: 0.0
    y: 0.0

  use_thin_strokes: true

render_timer: false

custom_cursor_colors: false

colors:
  primary:
    background: '0xeeeeee'
    foreground: '0x2e2e2d'

  normal:
    black:   '0x01130a'
    red:     '0xc62828'
    green:   '0x55b82f'
    yellow:  '0xf9a825'
    blue:    '0x1565c0'
    magenta: '0x6a1e9a'
    cyan:    '0x00838f'
    white:   '0xf2f2f2'

  bright:
    black:   '0x545454'
    red:     '0xef5350'
    green:   '0x8bc34a'
    yellow:  '0xffeb3b'
    blue:    '0x64b5f6'
    magenta: '0xba68c8'
    cyan:    '0x26c6da'
    white:   '0xe0e0e0'

visual_bell:
  animation: EaseOutExpo
  duration: 0

background_opacity: 1.0

selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>"

hide_cursor_when_typing: false

live_config_reload: true

key_bindings:
  - { key: V,    mods: Command, action: Paste      }
  - { key: C,    mods: Command, action: Copy       }
  - { key: Q,    mods: Command, action: Quit       }
  - { key: W,    mods: Command, action: Quit       }
  - { key: Back, mods: Alt,     chars:  "\x1b\x7f" }
  - { key: F,    mods: Alt,     chars:  "\x1bf"    }
  - { key: D,    mods: Alt,     chars:  "\x1bd"    }
  - { key: B,    mods: Alt,     chars:  "\x1bb"    }
